spring.application.name=openreachbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/openreach
spring.datasource.username=postgres
spring.datasource.password=960402

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true